### ISSUE TITLE
Exception when Database is Locked

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/pastebin-mirror#2]

**Comment by mpentler** [comment]
Is this still an issue? I’m looking for easy things to submit PRs for.

Does it need some basic error handling?

Edit: pasted wrong code snippet.

**Comment by mpentler** [comment]
Something like this: https://stackoverflow.com/questions/713794/catching-an-exception-while-using-a-python-with-statement

I know this was a while ago but do you have any traces?

**Comment by mpentler** [comment]
Oh wait: flatfile or sql? Or maybe it all needs some error handling?

Edit: Obviously SQL otherwise it wouldn't be a single file. I'm an idiot.

**Comment by brannondorsey** [comment]
Thanks for contributing. Sorry I let this slide for so long. I've been busy but I need to get better about entertaining offers of contribution from the community.

**Comment by mpentler** [comment]
Oh it’s fine! Like I said I’m quite new to contributing to projects so I was just looking for easy things to fix for people. Giving me a warm, fuzzy feeling. 

Seems adding error handling to people’s tools is a good niche to fill!

**Comment by mpentler** [comment]
And I only saw it and did it tonight anyway :p

**Comment by brannondorsey** [comment]
For some reason I read that first comment as having been from a few months ago, haha. Anyway, glad your making your first steps into contributing. Let me know if there is anything I can do to point you in any particular directions. :v:
