### ISSUE TITLE
Gracefully retry on network error

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/pastebin-mirror#6]
Currently, a network error or loss of internet connection will throw an exception and exit the program. This can be really annoying if you are downloading pastes for days or weeks at a time and small internet outages disrupt your archive. Ideally, there would be some graceful error handling that infinitely retries to fetch pastes at some timeout. Something like...

```
[!] unable to reach pastebin.com. Retrying in 1 minute...
```
That way brief outages or pastebin downtime won't crash the archiver indefinitely. @mpentler, is this something you would be interested in tackling (it should be pretty low hanging fruit ;)

**Comment by mpentler** [comment]
Retrying at intervals, eh? Would that override the rate currently set?

I don’t mind having a crack at this.

**Comment by brannondorsey** [comment]
Whoops, looks like I already implemented this in `scraper.py`. Errors print like `[!] Request to XXX returned non-200 code for paste YYY`. It really has been a while since I looked at this code. My bad.

**Comment by mpentler** [comment]
Surely that’s only partially done? I must admit I’ve not looked at scraper.py much yet but I thought it just printed the warning messages and returned None whenever it happened?

And again, I think there’s probably a question on where the code to manage this belongs. I’m thinking it doesn’t belong in the scraping module itself, but rather in main: if no data is received when you call for new pastes or trending pastes, then catch the exception and then do... whatever we want to do. 

Does that make sense?

**Comment by mpentler** [comment]
Eg: when I’m finished with it error checking on your while true loop is going to probably include a few excepts for catching sql errors and OSErrors, but could also check for other exceptions generated by scraper.py
