### ISSUE TITLE
Pastebin API changes due to April 27th

### ISSUE THREAD

**Issue by nanomader** [brannondorsey/pastebin-mirror#8]
There is small change in Pastebin API endpoints
https://pastebin.com/doc_scraping_api

![p](https://user-images.githubusercontent.com/7474972/39250828-1391e7c6-48a2-11e8-951e-bfd6b94d7325.png)

**Comment by jaegeral** [comment]
Any chance to get the urls updated? I tried it on my own but failed.

**Comment by brannondorsey** [comment]
Yes, I'll have a look at it this afternoon. Thank you both for bringing this to my attention. I've had the scraper running on a server for a few months and have sort of forgotten about it. I'm sure it's been erroring out for a while now. I'll ping here once it's updated.

**Comment by brannondorsey** [comment]
Updated the API urls and pushed a new version `v1.2.0`. Let me know if you are still having issues, otherwise thanks for the poke about this :smile_cat:.
